### ISSUE TITLE
[W3W] Fair SampleApp loading indicator 

### ISSUE THREAD

**Issue by flypaper0** [WalletConnect/WalletConnectSwiftV2#1266]
Currently pairing loading indicator disappears in 3 sec. Indicator should represent real pairing status

**Comment by arein** [comment]
can you pls link me to the code @flypaper0 ?
Looked at the [original PR](https://github.com/WalletConnect/WalletConnectSwiftV2/pull/942/files) and don't find the 3 second definition

**Comment by radeknovis** [comment]
@arein 
The timeout is set to 3 seconds in that PR in `Example/WalletApp/PresentationLayer/Wallet/Wallet/WalletPresenter.swift line #147` If we don't receive a session by that time it will show the timeout error, so it is timeout value rather than hardcoded time for how long to show loader. 
Referring to the PR, not sure about the current state as it seems like it's different code in develop.

**Comment by arein** [comment]
Gotcha. 3s timeout makes sense. AFK so not looking at code by maybe Artur's hypothesis of we show the loading until we get the first message was right. Instead we'd probably need to load until we received a or all 1100 tags.

**Comment by arein** [comment]
My initial bug report and what Pedro's video show is that after 3s we don't see an error

**Comment by radeknovis** [comment]
Yeah as I say the logic currently in develop is different from what is in the PR you've linked. It no longer shows the error message for some reason.

https://github.com/WalletConnect/WalletConnectSwiftV2/blob/bcecbd5af552cb9ee8dc125658614b5e8c878cc0/Example/WalletApp/PresentationLayer/Wallet/Wallet/WalletPresenter.swift#L130

**Comment by llbartekll** [comment]
added pairing state publisher, will be included in the next release
