### ISSUE TITLE
Use pre-made modal in native iOS (Dapp Support)

### ISSUE THREAD

**Issue by gracedmarks** [WalletConnect/WalletConnectSwiftV2#3]
From mobile linking qrcode-modal package, ```npm install --save @walletconnect/qrcode-modal```

Is it possible to use this in a native iOS app, in this case, Xcode project?

**Comment by MisterVants** [comment]
If I get your point correctly, you're asking if there's a default way provided to present a UI modal view to display the QR code.

Currently: No, the SDK doesn't provide a modal view to add into a native app or any other native UI utilities. 

However, that sounds like a very convenient feature that could help speed up developers in future integrations and experiments. I'll add it to our roadmap so that we can have some handy UI utilities in the future.

**Comment by gracedmarks** [comment]
Quick question -- can WalletConnectV2 protocol this flow?👇

Click connect in Swift app -> switch to MetaMask -> Sign -> Go back to our app with data and approval

**Comment by Ludotrico** [comment]
@MisterVants wondering the same thing ^

**Comment by MohsenKhosravinia** [comment]
@MisterVants same here

**Comment by llbartekll** [comment]
@gracedmarks could you provide more details what you want to do?

**Comment by ct222** [comment]
We also need native app to call wallet signature, transaction and other operations

**Comment by llbartekll** [comment]
@gracedmarks OK I think I know what you mean. You want your app to act like a dapp, establish a session with a wallet and then perform requests from your dapp to that wallet. So yes, that is possible, to do so you need to instantiate your client as a non-controller client.

**Comment by maurovz** [comment]
> Quick question -- can WalletConnectV2 protocol this flow?👇
> 
> Click connect in Swift app -> switch to MetaMask -> Sign -> Go back to our app with data and approval

I created a library that does this for V1 https://github.com/maurovz/Glaip
